### ISSUE TITLE
Node server connection timed out

### ISSUE THREAD

**Issue by burakoslu24** [matecat/MateCat#1930]
Everything was running perfectly after running the auto install script. Now when I try to run server.js I got this error:

debug: ** client error, restarting connection in 10 seconds Error: connect timed out
    at Client.Socket._createError (/home/matecat/cattool/nodejs/node_modules/stompit/lib/Socket.js:251:13)
    at Client.Socket.createTransportError (/home/matecat/cattool/nodejs/node_modules/stompit/lib/Socket.js:267:20)
    at Timeout.<anonymous> (/home/matecat/cattool/nodejs/node_modules/stompit/lib/connect.js:65:29)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

Any ideas? @Ostico

**Comment by burakoslu24** [comment]
Problem fixed by itself in time, but I still wonder why that happened.

**Comment by Ostico** [comment]
Thank you, I close.

**Comment by huangjeake** [comment]
i have the same problem when i run the auto install script, Client._createError (/var/www/matecat/nodejs/node_modules/stompit/lib/Socket.js:240:15)\\n    at Client.createTransportError (/var/www/matecat/nodejs/node_modules/stompit/lib/Socket.js:256:24)\\n    at Timeout.\u003canonymous\u003e (/var/www/matecat/nodejs/node_modules/stompit/lib/connect.js:95:29)\\n    at listOnTimeout (node:internal/timers:569:17)\\n    at process.processTimers (node:internal/timers:512:7)\"}\n","stream":"stdout","time":"2023-08-15T08:12:28.814592101Z"}  , i don't know how to solve it , can you help me? @Ostico
