### ISSUE TITLE
Installation Guide is Not Update.

### ISSUE THREAD

**Issue by kokoye2007** [matecat/MateCat#2048]
MateCat Installation Guide is Need to update.

Example Grunt Session is not relevant with current code repo.

**Comment by vasyugan** [comment]
Have you found a way around it? I tried to install it on an Ubuntu 18.04 virtual machine, in order to ensure that legacy packages that Matecat still depends on are still present, but still,I could not get beyond this point.

**Comment by kokoye2007** [comment]
Yes 
but many dependency
and you need to subscribe API access. (not sure but 2 or more api) 

and code is base on old stack (example php5*)

If you still interest ? I will send to you.

**Comment by Ostico** [comment]
We are planning to update the guide.

**Comment by vasyugan** [comment]
> Yes
> but many dependency
> and you need to subscribe API access. (not sure but 2 or more api)
> 
> and code is base on old stack (example php5*)
> 
> If you still interest ? I will send to you.

I am not sure what you mean by "
and you need to subscribe API access. (not sure but 2 or more api)"


But sure I am still interested in getting it up and running in a self-hosted manner. Currently we are using matecat.com. Do you happen to know if the open source version is fully compatible? I am asking because we use WMPL to connect WordPress with Matecat.

**Comment by vasyugan** [comment]
> We are planning to update the guide.

Great!!! But that probably doesn't change the fact that it still relies on PHP 5.*, so I guess the only viable option for deploying Matecat would be a docker image  and a docker-compose.yml, as you don't want to run an EOL version of PHP on your bare metal server. Are you thinking in in this direction?

**Comment by Ostico** [comment]
@vasyugan for now please refer to this:

https://github.com/matecat/MateCat/issues/1755

**Comment by endervad** [comment]
I'd like to up this issue since it's still not addressed. I'll also point a few more points that that bar the installation process from zero:

1. "Configure MySql" step:
`query_cache_limit` and `query_cache_size` parameters are removed from MySQL 8.
In `sql-mode` `NO_AUTO_CREATE_USER` was also removed.
Until you remove these, MySQL service will not start.

2. "Insall MateCat" step:
At `mysql -u root -p < matecat.sql` this step fails on Ubuntu 20.04 LTS with syntax error on line 1354. This could be because of my several failed attempts to start MySQL due to errors in point 1 though, I didn't bother to reinstall and check. This command succeeded on Ubuntu 18.04 LTS but I also fixed errors in advance so MySQL didn't have any errors.

3. "Configure MateCat" step:
`cp config.ini.sample config.ini` was probably also meant to be there since there's `sed -i "s/\/home\/matecat\/storage/\/home\/matecat\/cattool\/storage/g" config.ini` after that.

4. "Compile JS code" step:
It's a very minor one, but `cd /home/matecat/cattool/support_scripts/grunt` fails due to missing `grunt` folder. I just `mkdir`ed it.

And then I got stuck again on "Compile JS code" step at `npm install`. This is probably related to the issue discussed here I'm guessing, but despite doing steps from #1755 it still fails. The end of the log file looks like this:
```
6441 warn react-tiny-virtual-list@2.2.0 requires a peer of react@15.x || 16.x but none is installed. You must install peer dependencies yourself.
6442 warn react-tagsinput@3.19.0 requires a peer of react@^16.0.0 || ^15.0.0 || ^0.14.0 but none is installed. You must install peer dependencies yourself.
6443 warn eslint-plugin-jest@24.7.0 requires a peer of @typescript-eslint/eslint-plugin@>= 4 but none is installed. You must install peer dependencies yourself.
6444 warn jest@27.4.5 requires a peer of node-notifier@^8.0.1 || ^9.0.0 || ^10.0.0 but none is installed. You must install peer dependencies yourself.
6445 warn jest-cli@27.4.5 requires a peer of node-notifier@^8.0.1 || ^9.0.0 || ^10.0.0 but none is installed. You must install peer dependencies yourself.
6446 warn acorn-jsx@5.3.2 requires a peer of acorn@^6.0.0 || ^7.0.0 || ^8.0.0 but none is installed. You must install peer dependencies yourself.
6447 warn tsutils@3.21.0 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
6448 warn @jest/core@27.4.5 requires a peer of node-notifier@^8.0.1 || ^9.0.0 || ^10.0.0 but none is installed. You must install peer dependencies yourself.
6449 warn @jest/reporters@27.4.5 requires a peer of node-notifier@^8.0.1 || ^9.0.0 || ^10.0.0 but none is installed. You must install peer dependencies yourself.
6450 warn jest-config@27.4.5 requires a peer of ts-node@>=9.0.0 but none is installed. You must install peer dependencies yourself.
6451 warn jsdom@16.7.0 requires a peer of canvas@^2.5.0 but none is installed. You must install peer dependencies yourself.
6452 warn ws@7.5.6 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
6453 warn ws@7.5.6 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
6454 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
6455 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
6456 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
6456 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
6456 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
6456 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
6457 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
6458 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
6459 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
6459 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
6459 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
6459 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
6460 verbose stack Error: node-sass@6.0.1 postinstall: `node scripts/build.js`
6460 verbose stack Exit status 1
6460 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v9.11.2/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
6460 verbose stack     at EventEmitter.emit (events.js:180:13)
6460 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v9.11.2/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
6460 verbose stack     at ChildProcess.emit (events.js:180:13)
6460 verbose stack     at maybeClose (internal/child_process.js:936:16)
6460 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
6461 verbose pkgid node-sass@6.0.1
6462 verbose cwd /home/matecat/cattool/support_scripts/grunt
6463 verbose Linux 4.15.0-163-generic
6464 verbose argv "/root/.nvm/versions/node/v9.11.2/bin/node" "/root/.nvm/versions/node/v9.11.2/bin/npm" "install"
6465 verbose node v9.11.2
6466 verbose npm  v5.6.0
6467 error code ELIFECYCLE
6468 error errno 1
6469 error node-sass@6.0.1 postinstall: `node scripts/build.js`
6469 error Exit status 1
6470 error Failed at the node-sass@6.0.1 postinstall script.
6470 error This is probably not a problem with npm. There is likely additional logging output above.
6471 verbose exit [ 1, true ]
```
I can attach full log file if needed.
My OS is clean install of Ubuntu Server 18.04 LTS currently.

**Comment by Ostico** [comment]
Hi @endervad , thank you for MySQL 8 info.

Regarding JS code, we changed the install position.

Please, try to run `yarn install` in the root install dir.

Ex: 
`cd /home/matecat/cattool/ && yarn install`

**Comment by endervad** [comment]
@Ostico Thanks, but it didn't work unfortunately:
`[Errno 2] No such file or directory: 'install'`
Pointing at INSTALL directory with `yarn INSTALL` leads to
`[Errno 21] Is a directory: 'INSTALL'`
I also needed to install `yarn` first via `apt install cmdtest`.

**Comment by Ostico** [comment]
Please try:

```
npm install -g yarn
cd /home/matecat/cattool/
yarn install
grunt deploy
```

**Comment by endervad** [comment]
Now `yarn install` failed with
```
error get-caller-file@2.0.5: The engine "node" is incompatible with this module. Expected version "6.* || 8.* || >= 10.*". Got "9.11.2"
error Found incompatible module.
```
This specific version of Node.js was mentioned on "Install Node 9.11.2" step of the guide. Which one would be better to install now?

**Comment by Ostico** [comment]
You musty use a  `>= 10` version.

**Comment by endervad** [comment]
So for now I've come to this.
`yarn` now requires even higher version of `node` - at least 12.x. I've uninstalled other versions of `node` and installed only 12 and set it as default, so it looks like this:
```
root@matecat18:/home/matecat/cattool# nvm ls
->     v12.22.8
default -> node (-> v12.22.8)
node -> stable (-> v12.22.8) (default)
stable -> 12.22 (-> v12.22.8) (default)
iojs -> N/A (default)
find: warning: Unix filenames usually don't contain slashes (though pathnames do).  That means that '-name ‘lts/argon.*’' will probably evaluate to false all the time on this system.  You might find the '-wholename' test more useful, or perhaps '-samefile'.  Alternatively, if you are using GNU grep, you could use 'find ... -print0 | grep -FzZ ‘lts/argon.*’'.
lts/* -> lts/argon (-> N/A)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.17.0 (-> N/A)
lts/dubnium -> v10.24.1 (-> N/A)
lts/erbium -> v12.22.8
lts/fermium -> v14.18.2 (-> N/A)
lts/gallium -> v16.13.1 (-> N/A)
```
Then I roughly followed the guide again with your additions and internet advices, since `grunt deploy` initially didn't work because `grunt` wasn't installed:
```
cd /home/matecat/cattool
npm config set user 0
npm config set unsafe-perm true
npm install --save-dev @babel/core
npm install --save-dev webpack@2
rm -rf node_modules
npm install
npm install grunt
npm install -g grunt-cli
npm install -g yarn
yarn install
grunt deploy
```
According to the guide it was needed then to change the contents of `./nodejs/config.ini` with the one provided in the guide. So I did that while changing `your_domain.com` to my domain name.
The rest of the steps went fine but `server.js` didn't start - the script wasn't able to find `allowedOrigins[]` in `config.ini`. Apparently it was removed at the step "Configure MateCat". So I added it back from the repo version of the file, ran `server.js` again and got this:
```
root@matecat18:/home/mate# node /home/matecat/cattool/nodejs/server.js
{"message":"Listening on http://0.0.0.0:7788/","level":"debug"}
{"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":61613,"connectArgs":{"host":"localhost","port":"61613","timeout":3000,"connectHeaders":{"host":"/","login":"admin","passcode":"admin","heart-beat":"5000,5000"}},"level":"debug","message":"** client error, restarting connection in 10 seconds connect ECONNREFUSED 127.0.0.1:61613","stack":"Error: connect ECONNREFUSED 127.0.0.1:61613\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)"}
```
I also tried to use the sample `config.ini` as is, except changing `localhost`s to my domain like in the guide. The result is the same.
Meanwhile the web UI seems to be working but uploading a valid file leads to "Error: Server error, try again."

**Comment by Ostico** [comment]
Hi @endervad 
you are using amq/node on the same server machine? If so, can you paste here the `./nodejs/config.ini` file?

Nodejs can't connect to your AMQ.

**Comment by endervad** [comment]
```
root@matecat18:/home/matecat/cattool# cat ./nodejs/config.ini
[server]
address = 0.0.0.0
port = 7788
path = /channel/updates

[queue]
name = /topic/matecat_sse_notifications
host = localhost

port = 61613
login = admin
passcode = admin

[log]
file = log/server.log
level = debug

[cors]
allowedOrigins[] = https://localhost
allowedOrigins[] = http://localhost
```
Everything is on the same machine, yes. And I've set up ActiveMQ exactly by the guide, there were no problems there.
According to `activemq status` it turns out that the service doesn't start after the server reboot. So after `activemq start`, the `server.js` indeed didn't generate errors anymore. However, I still have "Error: Server error, try again." when I upload an XLSX file.

**Comment by Ostico** [comment]
@endervad this is normal, with the open source version ( and without a subscription to the matecat filters through RapidAPI ) you can convert/use only xliff files.

**Comment by xYuGeeN** [comment]
Good morning,
I have an error downloading your tool on an ubuntu 18. When I follow all the steps. The .html files are not in the documentRoot on matecat folder. 
Apache2 works fine, but it gives me error 500 because there are no files. Could you help me.
Please. Thanks,
Manu

**Comment by groundcat** [comment]
> * "Configure MySql" step:
>   `query_cache_limit` and `query_cache_size` parameters are removed from MySQL 8.
>   In `sql-mode` `NO_AUTO_CREATE_USER` was also removed.
>   Until you remove these, MySQL service will not start.
> * "Insall MateCat" step:
>   At `mysql -u root -p < matecat.sql` this step fails on Ubuntu 20.04 LTS with syntax error on line 1354. This could be because of my several failed attempts to start MySQL due to errors in point 1 though, I didn't bother to reinstall and check. This command succeeded on Ubuntu 18.04 LTS but I also fixed errors in advance so MySQL didn't have any errors.

I had the same error and it turns out to be a MySQL version issue. It's perhaps only compatible with MySQL 5.7. 

I followed this guide and successfully installed it on Ubuntu 20. Force install MySQL 5.7.

1. Follow the steps up to Step 1.5 here https://www.devart.com/dbforge/mysql/how-to-install-mysql-on-ubuntu/
2. `apt install -f mysql-client=5.7* mysql-server=5.7*`

**Comment by phea3** [comment]
The install guide makes it look easy, but the hard work comes next,
I struggled for 8 days trying to identify issues that aren't in the docs - login issues, SMTP errors and timeouts, the server crashing immediately after I installed it, config issues, etc.
The open-source version has no official support and there is little beyond basic documentation for other users.
If you intend to self-host, just know that it takes real patience and you need to persist. Be gentle with yourself
