### ISSUE TITLE
Uncaught exception becasue missing environment variables

### ISSUE THREAD

**Issue by tienhuynh17** [matecat/MateCat#3168]
Hello, thanks for your great open source!

**PROBLEM DESCRIPTION:**
I am trying to install MateCate in my server (Ubuntu 20.04) by following this guide: https://site.matecat.com/installation-guide
Everything work fine until I go to the root path of my domain to access MateCat: `https://<my_domain>/`, I got 500 error with following error Apache logs:
`
PHP Fatal error:  Uncaught exception 'StompException' with message 'Bad Broker URL ' in /home/sysadmin/matecat/lib/Utils/Stomp.php:107\nStack trace:\n#0 /home/sysadmin/matecat/lib/Utils/Stomp.php(80): Stomp->_init()\n#1 /home/sysadmin/matecat/lib/Utils/AMQHandler.php(43): Stomp->__construct(NULL)\n#2 /home/sysadmin/matecat/lib/Utils/Utils.php(375): AMQHandler->__construct()\n#3 /home/sysadmin/matecat/inc/Bootstrap.php(284): Utils::sendErrMailReport('#0  Bootstrap::...')\n#4 [internal function]: Bootstrap::shutdownFunctionHandler()\n#5 {main}\n  thrown in /home/sysadmin/matecat/lib/Utils/Stomp.php on line 107
`

**MY EFFORTS:**
I researched the code and knew that the `QUEUE_BROKER_ADDRESS` variable is invalid, so I tried:
- Make sure the variable exists in `inc/config.ini`
- Using PHP 7.4 instead of 5.6
- Edit code by adding missing env (`public static $QUEUE_BROKER_ADDRESS ='tcp://localhost:61613';`) in `inc/INIT.php`. The above error disappeared but another missing env error appear:
`PHP Fatal error:  Uncaught exception 'Exception' with message 'Missing task runner config' in /home/sysadmin/matecat/lib/Utils/WorkerClient.php:39\nStack trace:\n#0 /home/sysadmin/matecat/lib/Utils/Utils.php(375): WorkerClient::init(Object(AMQHandler))\n#1 /home/sysadmin/matecat/inc/Bootstrap.php(284): Utils::sendErrMailReport('#0  Bootstrap::...')\n#2 [internal function]: Bootstrap::shutdownFunctionHandler()\n#3 {main}\n  thrown in /home/sysadmin/matecat/lib/Utils/WorkerClient.php on line 39`
- Tried branch: `2.20.158`, `develop`, `master`.

**Additional information:**
- My apache configuration:
```
<VirtualHost *:80>
 ServerName <my_domain>
 RewriteEngine On
 RewriteCond %{HTTPS} !=on
 RewriteCond %{SERVER_PORT} 80
 RewriteCond %{HTTP_HOST} ^(.*)$
 RewriteRule ^/(.*)$ https://%1/$1 [R]
</VirtualHost>

<VirtualHost *:443>


 ServerAdmin webmaster@localhost
 ServerName <my_domain>

 DocumentRoot /home/myuser/matecat
 DirectoryIndex index.php index.php3 index.html index.htm index.shtml
 <Directory />
 Options FollowSymLinks
 AllowOverride None
 </Directory>

 SSLEngine On
 SSLProtocol all -SSLv3 -SSLv2

 SSLProxyEngine On

 SSLCertificateFile /path-to-my-cert-file
 SSLCertificateKeyFile /path-to-my-cert-file

 <Directory /home/myuser/matecat/ >

 Options All
 AllowOverride All
 Require all granted


 ExpiresActive On
 ExpiresByType text/html "access plus 1 minute"
 ExpiresByType text/css "access plus 1 minute"
 ExpiresByType text/javascript "access plus 1 minute"
 ExpiresByType image/gif "access plus 1 week"
 ExpiresByType image/jpeg "access plus 1 week"
 ExpiresByType image/jpg "access plus 1 week"
 ExpiresByType image/png "access plus 1 week"
 ExpiresByType image/vnd.microsoft.icon "access plus 1 week"
 ExpiresByType image/ico "access plus 1 week"
 ExpiresByType application/x-shockwave-flash "access plus 1 week"


 </Directory>

 php_flag register_globals off
 php_flag magic_quotes_gpc off
 ErrorLog ${APACHE_LOG_DIR}/matecat/error.log
 CustomLog ${APACHE_LOG_DIR}/matecat/access.log combined
 ServerSignature Off


 <Location /sse/ >
 ProxyPass http://localhost:7788/
 ProxyPassReverse http://localhost:7788/
 </Location>


</VirtualHost>
```

- When I go to no-root path (like /sse), the 404 page appear.
![image](https://github.com/matecat/MateCat/assets/39383420/85912f2b-e404-4fca-945c-e6e959dad0ad)

If you need more information, I will try to provide it.
I would greatly appreciate any help!

**Comment by riccio82** [comment]
The /sse path does not exist in Matecat.
Can you navigate to the root page and create projects?

**Comment by tienhuynh17** [comment]
Thanks for your reply, when I navigate to the root page, I got the error as I described in PROBLEM DESCRIPTION. (The 404 error I mentioned just is a additional information).

**Comment by tienhuynh17** [comment]
task_manager_config.ini file is already in the /inc folder.

![image](https://github.com/matecat/MateCat/assets/39383420/5485b1a4-9131-443f-a817-2731d9125c6f)

The file's content (copied from task_manager_config.ini.sample):
```
; Tasks definition file

loggerName = 'TaskManager.log'             ;Master Logger for the Task Manager

;;####################################
;;######  Executors Definition  ######
;;####################################
[context_definitions]

;;########## ANALYSIS ##########
;;###### Configuration by  #####
;;######      Key Name     #####
;;##############################
;;##############################
;;######    Key Name P1    #####
;;##############################
P1[queue_name]    = "analysis_queue_P1"         ;AMQ queue name
P1[pid_set_name]  = "ch_pid_set_p1"             ;Redis set list for the processes id
P1[max_executors] = 10                          ;Number of executors
P1[redis_key]     = "p1_list"                   ;Redis list of MateCat projects to be analyzed
P1[loggerName]    = "tm_analysis_P1.log"        ;Logger name
;;##############################
;;######    Key Name P2    #####
;;##############################
P2[queue_name]    = "analysis_queue_P2"
P2[pid_set_name]  = "ch_pid_set_p2"
P2[max_executors] = 5
P2[redis_key]     = "p2_list"
P2[loggerName]    = "tm_analysis_P2.log"
;;##############################
;;######    Key Name P3    #####
;;##############################
P3[queue_name]    = "analysis_queue_P3"
P3[pid_set_name]  = "ch_pid_set_p3"
P3[max_executors] = 1
P3[redis_key]     = "p3_list"
P3[loggerName]    = "tm_analysis_P3.log"

;;##################################
;;##### Key Name project_queue #####
;;##################################
PROJECT_QUEUE[queue_name]    = "project_queue"
PROJECT_QUEUE[pid_set_name]  = "ch_pid_project_queue"
PROJECT_QUEUE[max_executors] = 1
PROJECT_QUEUE[redis_key]     = "project_queue_list"
PROJECT_QUEUE[loggerName]    = "project_queue.log"

;;##############################
;;##### Key Name MailQueue #####
;;##############################
MAIL[queue_name]    = "mail_queue"
MAIL[pid_set_name]  = "ch_pid_set_mail"
MAIL[max_executors] = 1
MAIL[redis_key]     = "mail_list"
MAIL[loggerName]    = "mail_queue.log"

;;##############################
;;##### Key Name setContribution #####
;;##############################
CONTRIBUTION[queue_name]    = "set_contribution"
CONTRIBUTION[pid_set_name]  = "ch_pid_set_contribution"
CONTRIBUTION[max_executors] = 1
CONTRIBUTION[redis_key]     = "set_contribution_list"
CONTRIBUTION[loggerName]    = "set_contribution.log"

;;##############################
;;##### Key Name QAChecks  #####
;;##############################
QA_CHECKS[queue_name] = "qa_checks"
QA_CHECKS[pid_set_name] = "qa_checks_set"
QA_CHECKS[max_executors] = 1
QA_CHECKS[redis_key] = "qa_checks_key"
QA_CHECKS[loggerName] = "qa_checks.log"

;;#################################
;;##### Key Name activity_log #####
;;#################################
ACTIVITYLOG[queue_name]    = "activity_log"
ACTIVITYLOG[pid_set_name]  = "ch_pid_activity_log"
ACTIVITYLOG[max_executors] = 1
ACTIVITYLOG[redis_key]     = "activity_log_list"
ACTIVITYLOG[loggerName]    = "activity_log.log"

;;##############################
;;##### Key Name DQF       #####
;;##############################
DQF[queue_name]    = "dqf"
DQF[pid_set_name]  = "ch_pid_dqf"
DQF[max_executors] = 1
DQF[redis_key]     = "dqf_list"
DQF[loggerName]    = "dqf.log"


;;######################################
;;##### Key Name setContributionMT #####
;;######################################
CONTRIBUTION_MT[queue_name]    = "set_contribution_mt"
CONTRIBUTION_MT[pid_set_name]  = "ch_pid_set_contribution_mt"
CONTRIBUTION_MT[max_executors] = 1
CONTRIBUTION_MT[redis_key]     = "set_contribution_mt_list"
CONTRIBUTION_MT[loggerName]    = "set_contribution_mt.log"

;;##############################
;;##### Key Name jobs      #####
;;##############################
JOBS[queue_name]    = "jobs"
JOBS[pid_set_name]  = "ch_pid_jobs"
JOBS[max_executors] = 1
JOBS[redis_key]     = "jobs_list"
JOBS[loggerName]    = "jobs.log"


;;###############################
;;##### Key Name tmx import #####
;;###############################
;ALIGNER_TMX_IMPORT[queue_name]   = "aligner_tmx_import"
;ALIGNER_TMX_IMPORT[pid_set_name]  = "ch_pid_tmx_import"
;ALIGNER_TMX_IMPORT[max_executors] = 1
;ALIGNER_TMX_IMPORT[redis_key]     = "tmx_import_list"
;ALIGNER_TMX_IMPORT[loggerName]    = "tmx_import.log"

;;##############################
;;##### Key Name setContribution #####
;;##############################
CONTRIBUTION_GET[queue_name]    = "get_contribution"
CONTRIBUTION_GET[pid_set_name]  = "ch_pid_get_contribution"
CONTRIBUTION_GET[max_executors] = 50
CONTRIBUTION_GET[redis_key]     = "get_contribution_list"
CONTRIBUTION_GET[loggerName]    = "get_contribution.log"

;;###############################
;;#####   Align Job Small   #####
;;###############################
ALIGNER_ALIGN_JOB_SMALL[queue_name]    = "aligner_align_job_small"
ALIGNER_ALIGN_JOB_SMALL[pid_set_name]  = "ch_pid_align_job_small"
ALIGNER_ALIGN_JOB_SMALL[max_executors] = 1
ALIGNER_ALIGN_JOB_SMALL[redis_key]     = "align_job_small_list"
ALIGNER_ALIGN_JOB_SMALL[loggerName]    = "align_job_small.log"

;;###############################
;;#####   Align Job Medium  #####
;;###############################
ALIGNER_ALIGN_JOB_MEDIUM[queue_name]    = "aligner_align_job_medium"
ALIGNER_ALIGN_JOB_MEDIUM[pid_set_name]  = "ch_pid_align_job_medium"
ALIGNER_ALIGN_JOB_MEDIUM[max_executors] = 1
ALIGNER_ALIGN_JOB_MEDIUM[redis_key]     = "align_job_medium_list"
ALIGNER_ALIGN_JOB_MEDIUM[loggerName]    = "align_job_medium.log"

;;###############################
;;#####    Align Job Big    #####
;;###############################
ALIGNER_ALIGN_JOB_BIG[queue_name]    = "aligner_align_job_big"
ALIGNER_ALIGN_JOB_BIG[pid_set_name]  = "ch_pid_align_job_big"
ALIGNER_ALIGN_JOB_BIG[max_executors] = 1
ALIGNER_ALIGN_JOB_BIG[redis_key]     = "align_job_big_list"
ALIGNER_ALIGN_JOB_BIG[loggerName]    = "align_job_big.log"

;;###############################
;;#####   Segment Create    #####
;;###############################
ALIGNER_SEGMENT_CREATE[queue_name]    = "aligner_segment_create"
ALIGNER_SEGMENT_CREATE[pid_set_name]  = "ch_pid_aligner_segment_create"
ALIGNER_SEGMENT_CREATE[max_executors] = 5
ALIGNER_SEGMENT_CREATE[redis_key]     = "aligner_segment_create_list"
ALIGNER_SEGMENT_CREATE[loggerName]    = "aligner_segment_create.log"

;;##################################
;;##### Key Name GlossaryRead  #####
;;##################################
GLOSSARY_READ[queue_name]    = "glossary_read"
GLOSSARY_READ[pid_set_name]  = "ch_pid_glossary_read"
GLOSSARY_READ[max_executors] = 1
GLOSSARY_READ[redis_key]     = "glossary_read"
GLOSSARY_READ[loggerName]    = "glossary_read.log"

;;###################################
;;##### Key Name GlossaryWrite  #####
;;###################################
GLOSSARY_WRITE[queue_name]    = "glossary_write"
GLOSSARY_WRITE[pid_set_name]  = "ch_pid_glossary_write"
GLOSSARY_WRITE[max_executors] = 1
GLOSSARY_WRITE[redis_key]     = "glossary_write"
GLOSSARY_WRITE[loggerName]    = "glossary_write.log"

;;###################################
;;##### AI Assistant            #####
;;###################################
AI_ASSISTANT_EXPLAIN_MEANING[queue_name]    = "ai_assistant_explain_meaning"
AI_ASSISTANT_EXPLAIN_MEANING[pid_set_name]  = "ch_pid_ai_assistant_explain_meaning"
AI_ASSISTANT_EXPLAIN_MEANING[max_executors] = 1
AI_ASSISTANT_EXPLAIN_MEANING[redis_key]     = "ai_assistant_explain_meaning"
AI_ASSISTANT_EXPLAIN_MEANING[loggerName]    = "ai_assistant_explain_meaning.log"
```

**Comment by Ostico** [comment]
Hi @tienhuynh17 

PHP 7.4 works well for us, as we also use it.

From your stack trace exception, seems that the variable `INIT::$TASK_RUNNER_CONFIG` is not set.

This variable should set in the file `Bootstrap.php` in line 84:

`INIT::$TASK_RUNNER_CONFIG = parse_ini_file( self::$_ROOT . DIRECTORY_SEPARATOR . 'inc/task_manager_config.ini', true );`

The original error in the config.ini file regarding the Uncaught exception `'StompException' with message 'Bad Broker URL'` seems odd to me since it should be loaded from the code in `Bootstrap.php` in line 28:

`self::$CONFIG = parse_ini_file( self::$_ROOT . DIRECTORY_SEPARATOR . 'inc/config.ini', true )`

Could you please check the permissions on those files? Are they accessible and readable by the Apache user/group?

**Comment by tienhuynh17** [comment]
The files's permissions are the reason. Thanks so much for your help!
