### ISSUE TITLE
Error while running yarn build:dev

### ISSUE THREAD

**Issue by Abdujabbar** [matecat/MateCat#3210]
Hello! 

I have followed all the instructions here:

https://site.matecat.com/installation-guide#createcert

And at the end, when I run the command

` yarn build:dev`

I got next error: 

```$ webpack --mode development
[webpack-cli] Error: ENOENT: no such file or directory, open './public/build/lxqlicense.js'
    at Object.openSync (node:fs:581:18)
    at matecatConfig (/home/matecat/matecat/webpack.config.js:48:21)
    at loadConfigByPath (/home/matecat/matecat/node_modules/webpack-cli/lib/webpack-cli.js:1445:37)
    at async WebpackCLI.loadConfig (/home/matecat/matecat/node_modules/webpack-cli/lib/webpack-cli.js:1515:38)
    at async WebpackCLI.createCompiler (/home/matecat/matecat/node_modules/webpack-cli/lib/webpack-cli.js:1781:22)
    at async WebpackCLI.runWebpack (/home/matecat/matecat/node_modules/webpack-cli/lib/webpack-cli.js:1877:20)
    at async Command.<anonymous> (/home/matecat/matecat/node_modules/webpack-cli/lib/webpack-cli.js:944:21)
    at async Command.parseAsync (/home/matecat/matecat/node_modules/webpack-cli/node_modules/commander/lib/command.js:935:5)
    at async Command.<anonymous> (/home/matecat/matecat/node_modules/webpack-cli/lib/webpack-cli.js:1356:13)
    at async Command.parseAsync (/home/matecat/matecat/node_modules/webpack-cli/node_modules/commander/lib/command.js:935:5) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: './public/build/lxqlicense.js'
}
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.```


Tried to find on internet the trouble but could not find the exact reason for the trouble. 

Can you please refer me? 


Here is my os details:

```
root@45:/home/matecat/matecat# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```


Maybe if you have a newer version of the instructions? let me know pls.

**Comment by riccio82** [comment]
Hi @Abdujabbar ,

You are right, there was a problem in the webpack configuration in case you don't have lexiqa licence. 
I fixed it on develop branch, shortly we will deploy to master.
Thanks!

**Comment by Abdujabbar** [comment]
Hello @riccio82 

Quick question, Is it possible now deploy it from develop branch? or better to wait for the new version on master?

**Comment by rbm2023** [comment]
Hello,

I have the same problem as @Abdujabbar  with the "yarn build:dev" search in the "webpack.config.js" file for the file and path './public/build/lxqlicense.js'  but it does not exist.

I see that you are already working on the issue, hopefully you will upload it soon, thank you very much for the good work you do.

In the Bump version 2.20.165 of yesterday is not yet included the upgrade.

Thanks a lot!

**Comment by riccio82** [comment]
Yes, the fix is included and is also on the master branch.
