### ISSUE TITLE
mt-server AssertionError: Use of un initialized value $tag in split.

### ISSUE THREAD

**Issue by safiaa1** [matecat/MateCat#367]
Hi everyone!

We have a problem with mt-server specially when it executes the detokenizer script detokenizer.perl,

The issue is reproduced by this request:
curl --data q="htoaster forks "--data source="en" --data target="fr" --data key="keytest" http://localhost:8081/translate

This is the full error:

```
INFO:translation_log:The server is working on kwargs[q]: htoaster forks 
INFO:translation_log:The server is working on repr(kwargs[q]): u'htoaster forks '
INFO:translation_log:The server is working on segid: '0000'
INFO:translation_log.popen:executing: ~/software/mtserver-adaptive/code/tokenizer/deescape-special-chars.perl
INFO:translation_log.popen:executing: ~/software/mtserver-adaptive/code/tokenizer/tokenizer.perl -b -l en
INFO:translation_log.popen:executing: ~/software/mtserver-adaptive/code/monolingual/accents.pl -b -l en
INFO:translation_log.popen:executing: /usr/bin/python -u ~/software/mtserver-adaptive/code/tags4moses/annotate_words.py
INFO:translation_log.popen:executing: ~/software/mtserver-adaptive/code/tags4moses/reinsert_forcetranslate.pl -b -moses
Accent v1
Language: en
Tokenizer Version 1.1
Language: en
Number of threads: 1
INFO:translation_log:Engine name for segid 0000 is system_baseline
INFO:translation_log:KEY: 'system_baseline'
INFO:translation_log.writer:NAME: |'system_baseline'|
INFO:translation_log.writer:writing to process: u'htoaster forks\n'

INFO:translation_log.writer:writing to process: segid:'0000'
The input contains a  tag:
Translating line 0  in thread id 140598032393984
INFO:translation_log.reader:reader read: [u'0', u'fourchettes |1-1| htoaster |0-0|']
INFO:translation_log.reader:looking for id 0 in 1 result queues
INFO:translation_log:Engine name: system_baseline
INFO:translation_log.popen:executing: /usr/bin/python ~/software/mtserver-adaptive/code/tags4moses/ibm1align.py ~/software/working/train/model//lex.en-fr ~/software/working/train/model//lex.fr-en -printXmlWordAlignment -printXmlPhraseAlignment
INFO:translation_log.popen:executing: ~/software/mtserver-adaptive/code/tags4moses/deannotate_words.pl -b -collapse -p
INFO:translation_log.popen:executing: ~/software/mtserver-adaptive/code/tokenizer/detokenizer.perl -b -l fr
Traceback (most recent call last):
File "~/software/mtserver-adaptive/code/tags4moses/ibm1align.py", line 145, in 
src_txt, tgt_txt, palign, tag, markup = parser.parse(line)
File "~/software/mtserver-adaptive/code/tags4moses/moparser.py", line 10, in parse
src, tag, tgt,xml = self.parse_moses_output(line)
File "~/software/mtserver-adaptive/code/tags4moses/moparser.py", line 21, in parse_moses_output
assert src_match
AssertionError
Use of uninitialized value $tag in split at ~/software/mtserver-adaptive/code/tags4moses/deannotate_words.pl line 86,  line 1.
INFO:translation_log:The server is returning: {"data": {"translations": [{"systemName": "system_baseline", "segmentID": "0000"}]}}
127.0.0.1 - -  "POST /translate HTTP/1.1" 200 85 "" "curl/7.35.0"
INFO:cherrypy.access.140448562613136:127.0.0.1 - -  "POST /translate HTTP/1.1" 200 85 "" "curl/7.35.0"  
```

Please any help to fix this.

Tank you in advance!

**Comment by Ostico** [comment]
Hi @safiaa1 ,
i'm sorry but this is not the MMT project/software. 

Please submit here only the issues related to MateCat project.


Thank you.
