### ISSUE TITLE
Exception: Engine 1 not found

### ISSUE THREAD

**Issue by infojunkie** [matecat/MateCat#6]
Using the 0.5.1 version, I am getting the following exception when I upload an XLIFF file and click "Analyze":
```
[ E_ERROR ]
INIT-> fatalErrorHandler (line:434) : 	Uncaught exception 'Exception' with message 'Engine 1 not found' in /app/lib/utils/Engine.php:36
INIT-> fatalErrorHandler (line:434) : Stack trace:
INIT-> fatalErrorHandler (line:434) : #0 /app/lib/utils/TMSService.php(34): Engine::getInstance(1)
INIT-> fatalErrorHandler (line:434) : #1 /app/lib/utils/ProjectManager.php(81): TMSService->__construct()
INIT-> fatalErrorHandler (line:434) : #2 /app/lib/controller/createProjectController.php(218): ProjectManager->__construct()
INIT-> fatalErrorHandler (line:434) : #3 /app/index.php(15): createProjectController->doAction()
INIT-> fatalErrorHandler (line:434) : #4 {main}
INIT-> fatalErrorHandler (line:434) :   thrown
INIT-> fatalErrorHandler (line:434) : 	Not Recoverable Error on line 36 in file /app/lib/utils/Engine.php - PHP 5.5.9-1ubuntu4.7 (Linux)
INIT-> fatalErrorHandler (line:434) :  - REQUEST URI: /?action=createProject&time=1427843506666,jid=undefined
INIT-> fatalErrorHandler (line:434) :  - REQUEST Message: Array
INIT-> fatalErrorHandler (line:434) : (
INIT-> fatalErrorHandler (line:434) :     [action] => createProject
INIT-> fatalErrorHandler (line:434) :     [time] => 1427843506666,jid=undefined
INIT-> fatalErrorHandler (line:434) :     [file_name] => xliff.xliff
INIT-> fatalErrorHandler (line:434) :     [project_name] => 
INIT-> fatalErrorHandler (line:434) :     [source_language] => en-US
INIT-> fatalErrorHandler (line:434) :     [target_language] => fr-FR
INIT-> fatalErrorHandler (line:434) :     [job_subject] => general
INIT-> fatalErrorHandler (line:434) :     [disable_tms_engine] => false
INIT-> fatalErrorHandler (line:434) :     [mt_engine] => 1
INIT-> fatalErrorHandler (line:434) :     [private_tm_key] => 
INIT-> fatalErrorHandler (line:434) :     [private_keys_list] => {"ownergroup":[],"mine":[],"anonymous":[]}
INIT-> fatalErrorHandler (line:434) :     [private_tm_user] => 
INIT-> fatalErrorHandler (line:434) :     [private_tm_pass] => 
INIT-> fatalErrorHandler (line:434) :     [lang_detect_files] => Array
fatalErrorHandler (line:434) :         (
INIT-> fatalErrorHandler (line:434) :             [xliff.xliff] => detect
INIT-> fatalErrorHandler (line:434) :         )
INIT-> fatalErrorHandler (line:434) : 
INIT-> fatalErrorHandler (line:434) : )
INIT-> fatalErrorHandler (line:434) : 
INIT-> fatalErrorHandler (line:434) : 
INIT-> fatalErrorHandler (line:434) : 	Aborting...

```

The same file works well on the hosted version. Any idea what I am doing wrong?

**Comment by matecat** [comment]
Hi @infojunkie ,
sorry, but a bug was present in SQL Database creation script.
I fixed it, now it should work.
Please re-create the database.

**Comment by infojunkie** [comment]
Thanks, works now.
