### ISSUE TITLE
db key errror

### ISSUE THREAD

**Issue by SynergiumEU** [matecat/MateCat#642]
hi, we are getting an error with version 113 setup, are we missing some moduel?

Failed to store segments in database for knowhow.docx

==> /var/log/apache2/matecat.error.log <==
[Mon Feb 13 11:34:45.724066 2017] [:error] [pid 1339] [client 10.0.1.163:51928] PHP Notice:  Trying to get property of non-object in /home/matecat/cattool/lib/Model/Database.php on line 293, referer: https://test.domain.e/
[Mon Feb 13 11:34:45.724112 2017] [:error] [pid 1339] [client 10.0.1.163:51928] PHP Notice:  Trying to get property of non-object in /home/matecat/cattool/lib/Model/Database.php on line 293, referer: https://test.domain.e/
[Mon Feb 13 11:34:45.757058 2017] [:error] [pid 1339] [client 10.0.1.163:51928] PHP Notice:  Array to string conversion in /home/matecat/cattool/lib/Utils/ProjectManager.php on line 1709, referer: https://test.domain.eu/

\\disk.domain.eu\matecat\test\log_archive\log.txt
[2017-02-13 10:34:45] MateCat.DEBUG: [2017-02-13 10:34:45 (10.0.1.163)] 7m32ec1jthgre  ProjectManager-> _extractSegments (line:1654) : Id sequence reserved.  
[2017-02-13 10:34:45] MateCat.DEBUG: [2017-02-13 10:34:45 (10.0.1.163)] 7m32ec1jthgre  ProjectManager-> _extractSegments (line:1700) : Segments: Total Queries to execute: 1  
[2017-02-13 10:34:45] MateCat.DEBUG: [2017-02-13 10:34:45 (10.0.1.163)] 7m32ec1jthgre  ProjectManager-> _extractSegments (line:1708) : Segment import - DB Error: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY' - 
[2017-02-13 10:34:45 (10.0.1.163)] 7m32ec1jthgre  ProjectManager-> _extractSegments (line:1708) :  
[2017-02-13 10:34:45] MateCat.DEBUG: [2017-02-13 10:34:45 (10.0.1.163)] 7m32ec1jthgre  ProjectManager-> createProject (line:479) : Segment import - DB Error: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1' for key 'PRIMARY' - Array  
[2017-02-13 10:34:45] MateCat.DEBUG: [2017-02-13 10:34:45 (10.0.1.163)] 7m32ec1jthgre  ProjectManager-> createProject (line:480) : #0 /home/matecat/cattool/lib/Utils/ProjectManager.php(431): ProjectManager->_extractSegments('<?xml version="...', '13', 'docx')
[2017-02-13 10:34:45 (10.0.1.163)] 7m32ec1jthgre  ProjectManager-> createProject (line:480) : #1 /home/matecat/cattool/lib/Controller/createProjectController.php(317): ProjectManager->createProject()
[2017-02-13 10:34:45 (10.0.1.163)] 7m32ec1jthgre  ProjectManager-> createProject (line:480) : #2 /home/matecat/cattool/index.php(8): createProjectController->doAction()
[2017-02-13 10:34:45 (10.0.1.163)] 7m32ec1jthgre  ProjectManager-> createProject (line:480) : #3 {main}  
[2017-02-13 10:34:45] MateCat.DEBUG: [2017-02-13 10:34:45 (10.0.1.163)] 7m32ec1jthgre  ProjectManager-> _doCheckForErrors (line:830) : Project Creation Failed. Sent to Output all errors.  
[2017-02-13 10:34:45] MateCat.DEBUG: [2017-02-13 10:34:45 (10.0.1.163)] 7m32ec1jthgre  ProjectManager-> _doCheckForErrors (line:831) : Array
[2017-02-13 10:34:45 (10.0.1.163)] 7m32ec1jthgre  ProjectManager-> _doCheckForErrors (line:831) : (
[2017-02-13 10:34:45 (10.0.1.163)] 7m32ec1jthgre  ProjectManager-> _doCheckForErrors (line:831) :     [0] => Array
[2017-02-13 10:34:45 (10.0.1.163)] 7m32ec1jthgre  ProjectManager-> _doCheckForErrors (line:831) :         (
[2017-02-13 10:34:45 (10.0.1.163)] 7m32ec1jthgre  ProjectManager-> _doCheckForErrors (line:831) :             [code] => -7
[2017-02-13 10:34:45 (10.0.1.163)] 7m32ec1jthgre  ProjectManager-> _doCheckForErrors (line:831) :             [message] => Failed to store segments in database for knowhow.docx
[2017-02-13 10:34:45 (10.0.1.163)] 7m32ec1jthgre  ProjectManager-> _doCheckForErrors (line:831) :         )
[2017-02-13 10:34:45 (10.0.1.163)] 7m32ec1jthgre  ProjectManager-> _doCheckForErrors (line:831) : 
[2017-02-13 10:34:45 (10.0.1.163)] 7m32ec1jthgre  ProjectManager-> _doCheckForErrors (line:831) : )
[2017-02-13 10:34:45 (10.0.1.163)] 7m32ec1jthgre  ProjectManager-> _doCheckForErrors (line:831) :

**Comment by SynergiumEU** [comment]
bump

**Comment by Ostico** [comment]
Hi @SynergiumEU ,
there are migrations on the database to do when you upgrade to a new matecat version.

Sorry, this feature is not documented. 
You have re-built you database from scratch when you upgraded MateCat or you just pulled the new sources from git?

Let me know, so i can help you.

**Comment by SynergiumEU** [comment]
I am tryiing to do a new install, after 10 installes, I noticed, that sometimes I dont get the error but then after the page refresh it comed back...

**Comment by SynergiumEU** [comment]
1.1.1h - working
1.1.2d - error
1.1.3b - error

**Comment by Ostico** [comment]
Hi @SynergiumEU 

can you try to re-create the database with this sql?

[matecat.sql.zip](https://github.com/matecat/MateCat/files/793152/matecat.sql.zip)

Let me know if worked.

**Comment by SynergiumEU** [comment]
is this 1.1.3 version?

**Comment by Ostico** [comment]
Yes!

**Comment by SynergiumEU** [comment]
cannot import db
ERROR 1075 (42000) at line 171: Incorrect table definition; there can be only one auto column and it must be defined as a key

**Comment by Ostico** [comment]
Oh, sorry, bad dump, this should work. Sorry for the inconvenience.

[matecat.sql.zip](https://github.com/matecat/MateCat/files/793757/matecat.sql.zip)

**Comment by SynergiumEU** [comment]
tested with 1.1.3b and it works
