### ISSUE TITLE
Exception when downloading the translation

### ISSUE THREAD

**Issue by uhallac** [matecat/MateCat#944]
When I try to download a translation file in a project using the download URL (in my MateCat instance), sometimes I'm getting the following exception:

> [08-Sep-2017 16:52:06 Europe/Rome] PHP Warning:  filesize(): stat failed for /home/matecat/cattool/storage/tmp_download/17107/18399/59b2ae75304b72.96032608_.out.b3fb988a40dce6ee6209e37f07a9bbf7.doc.sdlxliff in /home/matecat/cattool/lib/Utils/Filters.php on line 210
[08-Sep-2017 16:52:06 Europe/Rome] PHP Warning:  rename(/home/matecat/cattool/storage/tmp_download/17107/18399/59b2ae75304b72.96032608_.out.b3fb988a40dce6ee6209e37f07a9bbf7.doc.sdlxliff,/home/matecat/cattool/storage/conversion_errors/20170908/165206-59b2ae75304b72.96032608_.out.b3fb988a40dce6ee6209e37f07a9bbf7.doc.sdlxliff): No such file or directory in /home/matecat/cattool/lib/Utils/Filters.php on line 263
[08-Sep-2017 16:52:06 Europe/Rome] PHP Notice:  Undefined index: document_content in /home/matecat/cattool/lib/Controller/downloadFileController.php on line 257
[08-Sep-2017 16:52:06 Europe/Rome] PHP Fatal error:  Uncaught exception 'Exception' with message 'Error while retrieving input_filename content: /home/matecat/cattool/storage/tmp_download/17107/18399/59b2ae75304b72.96032608_.out.b3fb988a40dce6ee6209e37f07a9bbf7.doc.sdlxliff' in /home/matecat/cattool/lib/Model/ZipContentObject.php:24
Stack trace:
#0 /home/matecat/cattool/lib/Controller/downloadFileController.php(497): ZipContentObject->getContent()
#1 /home/matecat/cattool/lib/Controller/downloadFileController.php(381): downloadFileController->setContent(Object(ZipContentObject))
#2 /home/matecat/cattool/index.php(9): downloadFileController->doAction()
#3 {main}
  thrown in /home/matecat/cattool/lib/Model/ZipContentObject.php on line 24

The thing is it doesn't happen all the time, sometimes the file is downloaded without any issues. 

Any idea what might be causing this?

**Comment by Ostico** [comment]
Hi @uhallac , is finally broken or when you try again to download the same file it works?

**Comment by uhallac** [comment]
Hi @Ostico, I couldn't find the exact steps to reproduce this but it's a 800KB doc file and it takes about 1.5 minutes to download (not sure why it takes that long). I suspect multiple requests to download the file might be causing the issue.

**Comment by Ostico** [comment]
Hi @uhallac , it seems that the converted file does not exists on your server, maybe because the filters are not working and/or not responding.

**Comment by Ostico** [comment]
Can i close?

**Comment by uhallac** [comment]
sure
